version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=persondb,medicaldb,qrcodedb
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases.sh:/docker-entrypoint-initdb.d/docker-postgresql-multiple-databases.sh
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always
    depends_on:
      - zookeeper
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    restart: always
  api-gateway:
    build: ./api-gateway
    environment:
      EUREKA_URL: http://service-registry:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    ports:
      - "80:80"
    restart: always
    depends_on:
      - service-registry
  medical-service:
    build: ./medical-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medicaldb
      EUREKA_URL: http://service-registry:8761/eureka
      KAFKA_SERVER_ENDPOINT: kafka:29092
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    restart: always
    depends_on:
      - db
      - service-registry
  person-service:
    build: ./person-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/persondb
      EUREKA_URL: http://service-registry:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      - db
      - service-registry
  qr-service:
    build: ./qr-code-storage-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/qrcodedb
      EUREKA_URL: http://service-registry:8761/eureka
      KAFKA_SERVER_ENDPOINT: kafka:29092
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      - db
      - service-registry
volumes:
  dbdata:
